name: Build_R8125

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: jinlife-ubuntu-18.04
    name: Compile "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: apollolake
            version: "7.0"
          - platform: geminilake
            version: "7.0"

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
            ref: master

      - name: Checkout toolkit repository
        uses: actions/checkout@v2
        with:
          repository: SynologyOpenSource/pkgscripts-ng
          ref: DSM7.0
          path: pkgscripts-ng
        
      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E swapoff -a
          sudo -E rm -f /swapfile
          sudo -E docker image prune -a -f
          sudo -E snap set system refresh.retain=2
          sudo -E apt-get -y purge azure* dotnet* firefox ghc* google* hhvm llvm* mono* mysql* openjdk* php* zulu*
          sudo -E apt-get -y autoremove --purge
          sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /etc/mysql /etc/php /usr/local/share/boost
          [ -n "$AGENT_TOOLSDIRECTORY" ] && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo -E apt-get update -y
          sudo -E apt-get install -y python3 wget tar pinentry && ln -s /usr/bin/python3 /usr/local/bin/python
          sudo -E apt-get clean
          git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
          df -h

      # https://github.com/cwuensch/SynoBuild
      - name: Download DSM toolkit
        run: |
         sudo mkdir -p /toolkit/build_env/ds.${{matrix.platform}}-${{matrix.version}} /toolkit/source
         sudo rsync -aIv pkgscripts-ng/ /toolkit/pkgscripts-ng/
         sudo rsync -aIv pkgscripts-ng/ /pkgscripts-ng/
         cd /toolkit
         sudo wget -qO- https://downloads.sourceforge.net/project/dsgpl/toolkit/DSM${{matrix.version}}/base_env-${{matrix.version}}.txz | sudo tar -xJhv -C build_env/ds.${{matrix.platform}}-${{matrix.version}}
         sudo wget -qO- https://downloads.sourceforge.net/project/dsgpl/toolkit/DSM${{matrix.version}}/ds.${{matrix.platform}}-${{matrix.version}}.env.txz | sudo tar -xJhv -C build_env/ds.${{matrix.platform}}-${{matrix.version}}
         sudo wget -qO- https://downloads.sourceforge.net/project/dsgpl/toolkit/DSM${{matrix.version}}/ds.${{matrix.platform}}-${{matrix.version}}.dev.txz | sudo tar -xJhv -C build_env/ds.${{matrix.platform}}-${{matrix.version}}

      # http://www.wolfteck.com/2019/03/02/packaging_rtl88x2bu_for_synology_nas/
      # http://dd-han.tw/2018/synology-development-emviroment-create
      - name: ENV Prepare
        working-directory: /toolkit/pkgscripts-ng
        run: |
          sudo ./EnvDeploy -v ${{matrix.version}} --list
          ls /toolkit/build_env/ds.${{matrix.platform}}-${{matrix.version}}
          #sudo ./EnvDeploy -t toolkit_tarballs -v ${{matrix.version}} -p ${{matrix.platform}}
      
      # https://gist.github.com/woods/8970150
      - name: Copy Source
        run: |
         sudo svn export https://github.com/jinlife/unraid-r8125-r8152-driver/trunk/r8125 /toolkit/source/r8125
         sudo svn export https://github.com/jinlife/unraid-r8125-r8152-driver/trunk/r8152 /toolkit/source/r8152
         sudo patch -d /toolkit/source/r8152/src -p1 -i /toolkit/source/r8152/patches/100-add-LED-configuration-from-OF.patch
         sudo rsync -aIv /toolkit/source/r8125/src/  /toolkit/source/r8125/
         sudo rsync -aIv /toolkit/source/r8152/src/  /toolkit/source/r8152/
         sudo rsync -aIv ./build/r8152/  /toolkit/source/r8152/
         sudo rsync -aIv ./build/r8125/  /toolkit/source/r8125/
         sudo chmod -R 777 /toolkit/source
         sudo chmod -R 777 ./build/
         ls ./build/

      - name: Generate key
        run: |
            cat <<-EOF > genkey
                Key-Type: 1
                Key-Length: 4096
                Subkey-Type: 1
                Subkey-Length: 4096
                Name-Real: Testing name
                Name-Email: test@test.org
                Expire-Date: 0
                Passphrase: Test1234~
                %no-protection
            EOF
            sudo gpg --gen-key --batch genkey
            sudo rsync -aIv ~/.gnupg /toolkit/build_env/ds.${{matrix.platform}}-${{matrix.version}}/root/
            
      #- name: Make complie
      #  working-directory: /toolkit
      #  run: |
      #    cd /toolkit/source/r8125
      #    sudo ./INFO.sh > INFO
      #    cd /toolkit/source/r8152
      #    sudo ./INFO.sh > INFO
      #    #chroot /toolkit/build_env/ds.${{matrix.platform}}-${{matrix.version}}
      #    #sudo pkgscripts-ng/PkgCreate.py -p ${{matrix.platform}} -I r8125
      #    #sudo pkgscripts-ng/PkgCreate.py -p ${{matrix.platform}} -I r8152
      #    #sudo make oldconfig
      #    #sudo sed -i -e 's#CONFIG_SYSTEM_TRUSTED_KEYS="debian/canonical-certs.pem"#CONFIG_SYSTEM_TRUSTED_KEYS=""#g' .config
      #    #cat .config
      
      - name: Make Package
        working-directory: /toolkit
        run: |
          sudo pkgscripts-ng/PkgCreate.py -v ${{matrix.version}} -p ${{matrix.platform}} -c r8152
          sudo pkgscripts-ng/PkgCreate.py -v ${{matrix.version}} -p ${{matrix.platform}} -c r8125       
      
      - name: Compile Linux
        working-directory: /toolkit
        run: |
          echo 'root start'
          ls
          echo 'root end'
          ls result_spk
      
      - name: Find files
        run: |
          sudo rm -rf ./artifact
          sudo mkdir -p ./artifact
          sudo chmod -R 777 ./artifact
          sudo rsync -aIv /toolkit/result_spk/ ./artifact/ 

      - name: Upload github actions
        uses: actions/upload-artifact@v3
        with:
          name: ds.${{matrix.platform}}-${{matrix.version}}
          path: artifact/*
          if-no-files-found: error

      #- name: Delete old workflow
      #  uses: Mattraks/delete-workflow-runs@v2
      #  with:
      #    retain_days: 1
      #    keep_minimum_runs: 3
